version: '2.3'

services:
  caddy:
    image: caddy
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - ./.caddy/:/data
    ports:
      - 80:80
      - 443:443
    restart: always

  minio: 
    image: minio/minio
    command: server /data
    restart: always
    volumes:
      - /efi_neon_challenge:/data    
    env_file: ./config/minio_env.sh
    ports:
      - 9000:9000

  cron:
    build: 
      context: cron-container
    image: eco4cast/cron
    restart: always
    volumes:
      - ../scripts:/scripts
      - ./cron.d:/etc/cron.d
      - /efi_neon_challenge/log/cron:/var/log
      - /efi_neon_challenge:/efi_neon_challenge

  rstudio:
    image: rocker/geospatial
    restart: always
    volumes:
      - /efi_neon_challenge:/efi_neon_challenge
      - /home/cboettig/Documents:/home/rstudio/Documents
    env_file: ./config/rstudio_env.sh
    ports:
      - 8787:8787

  shiny:
    image: rocker/shiny-verse
    restart: always
    ports: 
      - 3838:3838
    volumes:
#     - ../shinyapp/:/srv/shiny-server
      - /efi_neon_challenge/log/shiny:/var/log/shiny-server

  ## not necessary, just for convenience 
  monitor:
    image: netdata/netdata  
    restart: always
    cap_add:
      - SYS_PTRACE
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    security_opt: 
      - apparmor=unconfined
    ports:
      - 19999:19999
